import { CHAIN } from '../src';

console.log('Cronos Chain Information', CHAIN.CRONOS.toHexChainInfo());
console.log('Cronos Chain Signature', CHAIN.CRONOS.getSignature());
console.log('Polygon Chain Information', CHAIN.POLYGON.toHexChainInfo());
console.log('Polygon Chain Signature', CHAIN.POLYGON.getSignature());
console.log('Optimism Chain Information', CHAIN.OPTIMISM.toHexChainInfo());
console.log('Optimism Chain Signature', CHAIN.OPTIMISM.getSignature());
console.log('Arbitrum Chain Information', CHAIN.ARBITRUM.toHexChainInfo());
console.log('Arbitrum Chain Signature', CHAIN.ARBITRUM.getSignature());
console.log('Avax C Chain Information', CHAIN.AVAXC.toHexChainInfo());
console.log('Avax C Chain Signature', CHAIN.AVAXC.getSignature());
console.log('Velas Information', CHAIN.VELAS.toHexChainInfo());
console.log('Velas Signature', CHAIN.VELAS.getSignature());
console.log('Fantom Information', CHAIN.FANTOM.toHexChainInfo());
console.log('Fantom Signature', CHAIN.FANTOM.getSignature());
console.log('Celo Information', CHAIN.CELO.toHexChainInfo());
console.log('Celo Signature', CHAIN.CELO.getSignature());
console.log('Aurora Information', CHAIN.AURORA.toHexChainInfo());
console.log('Aurora Signature', CHAIN.AURORA.getSignature());
console.log('Flare Information', CHAIN.FLARE.toHexChainInfo());
console.log('Flare Signature', CHAIN.FLARE.getSignature());
console.log('ThunderCore Information', CHAIN.THUNDERCORE.toHexChainInfo());
console.log('ThunderCore Signature', CHAIN.THUNDERCORE.getSignature());
console.log('OKX Information', CHAIN.OKX.toHexChainInfo());
console.log('OKX Signature', CHAIN.OKX.getSignature());
console.log('ZKS Information', CHAIN.ZKSYNC.toHexChainInfo());
console.log('ZKS Signature', CHAIN.ZKSYNC.getSignature());
