name: Check and publish npm packages

on:
  push:
    branches: [ master, stg*, hotfix*, beta, chore/update_bsc_for_trying_publish_npm ]

jobs:
  check_and_publish_npm_packages:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.DEVOPS_CW_SDK_DEVELOPMENT_TOKEN }}

    - name: Configure CI Git User
      run: |
        git config --global user.name 'coolwallet team'
        git config --global user.email 'cw.tech@coolbitx.com'

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16
        registry-url: 'https://registry.npmjs.org'

    - name: Publish action
      uses: ./.github/publish-action
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
