name: Update Changelog

on:
  push:
    tags:
      - '@coolwallet/*@*'

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Create changelog branch
        run: |
          # e.g. TAG_NAME=${TAG_NAME:-"@coolwallet/zen@2.0.0"}
          TAG_NAME=${GITHUB_REF#refs/tags/}
          
          if [[ "$TAG_NAME" =~ ^@coolwallet/(.+)@.* ]]; then
            PACKAGE_BASE="${BASH_REMATCH[1]}" 
            
            if [ -d "packages/$PACKAGE_BASE" ]; then
              PACKAGE_NAME="packages/$PACKAGE_BASE"
            else
              PACKAGE_NAME="packages/coin-$PACKAGE_BASE"
            fi
            
            BRANCH_NAME="docs/update-changelog-$PACKAGE_BASE"
          fi
          
          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          echo "PACKAGE_BASE=$PACKAGE_BASE" >> $GITHUB_ENV
          
          git checkout -b "$BRANCH_NAME"

      - name: Run script
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.DEVOPS_READ_PACKAGE_TOKEN }}
        run: bash scripts/update_changelog.sh "$TAG_NAME"

      - name: Commit and push changes
        run: |
          git config --global user.name 'coolwallet team'
          git config --global user.email 'cw.tech@coolbitx.com'
          git add packages/*/CHANGELOG.md
          git commit -m "docs: update changelog for $TAG_NAME"
          git push -u origin "$BRANCH_NAME"

      - name: Create Draft PR
        run: |
          
          gh pr create -d -B master \
            -t "docs($PACKAGE_BASE): update $TAG_NAME" -b ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}